version: '3.8'

networks:
  platform-net:
    driver: bridge

services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    networks:
      - platform-net
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
      - ./jmx-exporter-jar:/opt/jmx_exporter
      - ./jmx-exporter-config:/etc/jmx_exporter_config
    environment:
      # --- KRaft settings ---
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      # --- General Settings ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OPTS: "-javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=9991:/etc/jmx_exporter_config/kafka_jmx_config.yml"

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    networks:
      - platform-net
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_OPTS: "-javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=9993:/etc/jmx_exporter_config/sr_jmx_config.yml"
    volumes:
      - ./jmx-exporter-jar:/opt/jmx_exporter
      - ./jmx-exporter-config:/etc/jmx_exporter_config

  connect:
    image: confluentinc/cp-kafka-connect:7.6.1
    container_name: connect
    networks:
      - platform-net
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - schema-registry
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONNECT_GROUP_ID: 'connect-cluster-group'
      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-configs'
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-offsets'
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-status'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'connect'
      CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components'
      KAFKA_JMX_OPTS: "-javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=9992:/etc/jmx_exporter_config/connect_jmx_config.yml"
    volumes:
      - ./connectors/plugins:/usr/share/confluent-hub-components
      - ./jmx-exporter-jar:/opt/jmx_exporter
      - ./jmx-exporter-config:/etc/jmx_exporter_config

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - platform-net
    depends_on:
      - kafka
      - schema-registry
      - connect
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kraft
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_READONLY: "false"
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: 'http://schema-registry:8081'
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: 'local-connect'
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: 'http://connect:8083'

  elasticsearch:
    image: public.repo.smartech.ir/elasticsearch:8.13.4
    container_name: elasticsearch
    networks:
      - platform-net
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.name=platform-cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # --- سرویس اکسپورتر با ایمیج جدید ---
  elasticsearch-exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest # <--- ایمیج جدید جایگزین شد
    container_name: elasticsearch-exporter
    networks:
      - platform-net
    command:
      - '--es.uri=http://elasticsearch:9200'
      - '--es.all'
      - '--es.indices'
    ports:
      - "9114:9114"
    depends_on:
      - elasticsearch

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    networks:
      - platform-net
    ports:
      - "9308:9308"
    command:
      - "--kafka.server=kafka:29092"
    depends_on:
      - kafka

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - platform-net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - kafka-exporter
      - elasticsearch-exporter

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    networks:
      - platform-net
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  kafka_data:
  es_data:
  grafana_data: